const NOTIFICATIONS_TYPE = {
	REACTION_TO_POST: 'REACTION_TO_POST',
	NEW_FOLLOWER: 'NEW_FOLLOWER',
	NEW_MEMBER_GROUP: 'NEW_MEMBER_GROUP',
	PRIVATE_MESSAGE: 'PRIVATE_MESSAGE',
	COMMENT_ON_PICTURE: 'COMMENT_ON_PICTURE',
}

export { NOTIFICATIONS_TYPE }
